site_name: 欢迎加入浙江大学控制学院
site_url: https://zju-cse-academic.github.io/welcome-to-cse/

copyright: Copyright &copy; 2024 浙江大学控制科学与工程学院学生会学术部

nav: 
  - 主页:
    - index.md
  - 专业介绍: my-major/index.md
  - 培养方案: curriculum/index.md  # 培养方案概览
  #   - tri_fold_brochure.md  # 三折页
  #   - course_and_ideology_diagram.md  # 课程框图+思政培养框图
  # - QQ咨询群：
  #   - qq_group_qr_code.md  # QQ群二维码页面


# Configuration
theme:
  name: 'material'
  custom_dir: docs/overrides
  language: 'zh'
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - content.code.annotate
    - content.action.edit
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    # - header.autohide
    - toc.integrate

  palette:
    # Toggle light mode
    - scheme: default
      primary: md-primary-fg-color
      accent: md-primary-fg-color
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Toggle dark mode
    - scheme: slate
      primary: md-primary-fg-color
      accent: md-primary-fg-color
      toggle:
        icon: material/lightbulb
        name: Switch to light mode


  favicon: img/favicon.ico

markdown_extensions:
  - toc:
      permalink: false
      # slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true




# Repository
repo_name: ZJU-CSE-ACADEMIC/welcome-to-cse
repo_url: https://github.com/ZJU-CSE-ACADEMIC/welcome-to-cse


extra_css:
  - css/general.css
  - css/carousel.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

